DROP TABLE TB_MAPP_SEQ;
CREATE TABLE TB_MAPP_SEQ(
  SEQ_TYPE varchar(20),
  SEQ_NO int(11)
)
;
INSERT INTO TB_MAPP_SEQ(SEQ_TYPE, SEQ_NO) VALUES ('USER_SEQ', 0);
INSERT INTO TB_MAPP_SEQ(SEQ_TYPE, SEQ_NO) VALUES ('COURSE_SEQ', 0);
INSERT INTO TB_MAPP_SEQ(SEQ_TYPE, SEQ_NO) VALUES ('STUDENT_REG_SEQ', 0);
INSERT INTO TB_MAPP_SEQ(SEQ_TYPE, SEQ_NO) VALUES ('PROFESSOR_REG_SEQ', 0);

DROP TABLE TB_COM_CODE;
CREATE TABLE TB_COM_CODE(
  COMM_TY_CD varchar(10),
  COMM_CD varchar(20),
  COMM_CD_NM varchar(30),

  CONSTRAINT TB_CODE_PK PRIMARY KEY(COMM_TY_CD, COMM_CD)
);

-- 전화번호
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '01', '010');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '02', '011');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '03', '016');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0100', '04', '019');

-- 과목분류코드
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'ME', '전공필수');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'MO', '전공선택');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'RE', '교양필수');
INSERT INTO TB_COM_CODE(COMM_TY_CD, COMM_CD, COMM_CD_NM) VALUES('CODE0101', 'RO', '교양선택');


-- 회원정보
DROP TABLE TB_COM_USER;
CREATE TABLE TB_COM_USER(
  USER_CODE varchar(20),             --  유저코드
  ID varchar(20),                  --  아이디
  PW varchar(20),                   --  패스워드
  EMAIL varchar(50),                      --  이메일
  USER_IMAGE varchar(100),               --  유저이미지
  NAME varchar(20),                       --  이름
  BIRTH varchar(20),                      --  생일
  POST_NUM varchar(20),                   --  우편번호
  PHONE_CD varchar(2),                    --  전화번호앞자리 코드
  PHONE_NUM varchar(20),                  --  전화번호뒷자리
  ADDRESS varchar(100),                   --  주소
  ENT_DATE varchar(30),                   --  회원가입일
  GRADE varchar(1) DEFAULT 'S',			   --  회원등급
  CONSTRAINT TB_COM_USER_PK PRIMARY KEY(USER_CODE)
);

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, USER_IMAGE, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE, GRADE) VALUES (
          CONCAT('USER00000', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'USER_SEQ')) , 'admin', 'admin', 'admin@naver.com', 'admin.png', '관리자', '1961-01-28', '217-814',
          '01', '1434-8011', '서울시 송파구 방이동 현대아파트', '2015-11-21', 'A');
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'USER_SEQ';

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, USER_IMAGE, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE, GRADE) VALUES (
          CONCAT('USER00000', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'USER_SEQ')) , 'prof', 'prof', 'prof@naver.com', 'admin.png', '교수1', '1961-01-28', '217-814',
          '01', '1434-8011', '서울시 송파구 방이동 현대아파트', '2015-11-21', 'P');
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'USER_SEQ';

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, USER_IMAGE, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) VALUES (
          CONCAT('USER00000', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'USER_SEQ')), 'ranone', 'ranone', 'ranone@naver.com', 'ranone.png', '존레논', '1972-06-19', '151-241',
          '01', '8822-5318', '서울시 성동구 성수2동 롯데캐슬', '2015-11-21');
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'USER_SEQ';

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, USER_IMAGE, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) VALUES (
          CONCAT('USER00000', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'USER_SEQ')), 'love86n', 'love86n', 'love86n@naver.com', 'love86n.png', '헤더신', '1986-12-20', '391-756',
          '01', '0235-7912', '서울시 송파구 방이3동 유라상가', '2015-12-01');
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'USER_SEQ';

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, USER_IMAGE, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) VALUES (
          CONCAT('USER00000', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'USER_SEQ')), 'sawol', 'sawol', 'sawol@naver.com', 'sawol.png', '금사월', '1981-09-18', '157-995',
          '01', '1753-2718', '서울시 성북구 돈암1동 브라운스톤', '2014-03-17');
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'USER_SEQ';

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, USER_IMAGE, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) VALUES (
          CONCAT('USER00000', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'USER_SEQ')), 'ksy', 'ksy', 'ksy@naver.com', 'ksy.png', '기성용', '1989-01-12', '134-512',
          '01', '1326-2632', '서울시 중구 동대문4가 종로빌딩', '2015-10-30');
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'USER_SEQ';

INSERT INTO TB_COM_USER(USER_CODE, ID, PW, EMAIL, USER_IMAGE, NAME, BIRTH, POST_NUM, PHONE_CD, PHONE_NUM, ADDRESS, ENT_DATE) VALUES (
          CONCAT('USER00000', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'USER_SEQ')), 'shm', 'shm', 'shm@naver.com', 'shm.png', '손흥민', '1992-05-07', '613-844',
          '01', '5551-3774', '서울시 노원구 상계3동 한신아파트', '2012-08-02');
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'USER_SEQ';

commit;

-- 과목정보
DROP TABLE TB_COURSE;
CREATE TABLE TB_COURSE(
  COURSE_CODE varchar(20),                        -- 과목코드
  COURSE_NAME varchar(200),                       -- 과목명
  COURSE_SCORE int(11),			  		            -- 과목학점
  COURSE_CATEGORY_CD varchar(20),		            -- 과목분류
  COURSE_ASSIGN_YN varchar(20) DEFAULT 'N',       -- 과목 담당유무
  COURSE_MAX_NUMBER varchar(20),                  -- 과목정원
  COURSE_CUR_NUMBER varchar(20) DEFAULT 0,        -- 과목신청인원
  COURSE_CLASSROOM varchar(20),                   -- 교실
  COURSE_DAY varchar(20),                         -- 요일
  COURSE_PERIOD int(11), 							-- 교시
  COURSE_REG_DATE varchar(20),                     -- 과목개설일

  CONSTRAINT TB_COURSE_PK PRIMARY KEY(COURSE_CODE)
);

INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '영화의이해', 3, 'RO', 50, 'B101', '월', 1, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '프로그래밍언어', 3, 'RO', 40, 'B103', '화', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), 'C프로그래밍실습', 2, 'RO', 35, 'B102', '수', 2, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '시스템소프트웨어', 4, 'RE', 50, 'B104', '목', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '운영체제', 5, 'RE', 50, 'B105', '금', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '대학수학1', 6, 'RE', 40, 'B106', '월', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '대학수학2', 7, 'RE', 40, 'B107', '월', 2, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '공업수학1', 1, 'ME', 30, 'F201', '월', 1, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '공업수학2', 5, 'ME', 30, 'F301', '화', 2, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '법과사회', 5, 'ME', 40, 'F301', '월', 2, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '자연의이해', 2, 'ME', 50, 'F201', '수', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '대학영어1', 3, 'ME', 50, 'F201', '금', 1, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '대학영어2', 6, 'ME', 50, 'F202', '목', 2, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '자료구조', 7, 'ME', 30, 'F203', '목', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '알고리즘', 3, 'MO', 45, 'F204', '금', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '일본어기초', 3, 'MO', 35, 'F304', '금', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '웹프로그래밍실습', 3, 'MO', 55, 'F305', '금', 3, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '데이터베이스실습', 3, 'MO', 35, 'F501', '수', 2, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';
INSERT INTO TB_COURSE(COURSE_CODE, COURSE_NAME, COURSE_PERIOD, COURSE_CATEGORY_CD, COURSE_MAX_NUMBER, COURSE_CLASSROOM, COURSE_DAY, COURSE_SCORE, COURSE_REG_DATE)VALUES(CONCAT('C00', (SELECT COALESCE(MAX(SEQ_NO) + 1, 1) FROM TB_MAPP_SEQ WHERE SEQ_TYPE = 'COURSE_SEQ')), '인터넷프로그래밍', 3, 'MO', 40, 'F401', '월', 2, DATE_FORMAT(SYSDATE(), '%Y-%m-%d %H:%i'));
UPDATE TB_MAPP_SEQ SET SEQ_NO = SEQ_NO + 1 WHERE SEQ_TYPE = 'COURSE_SEQ';


-- 학생수강신청정보
DROP TABLE TB_STUDENT_REG;
CREATE TABLE TB_STUDENT_REG(
  STUDENT_REG_CODE varchar(20),   -- 학생수강신청 등록코드
  COURSE_CODE varchar(20),       -- 과목코드
  USER_CODE varchar(20),          -- 유저코드

  CONSTRAINT TB_STUDENT_REG_PK PRIMARY KEY(STUDENT_REG_CODE)
);

-- 교수담당과목정보
DROP TABLE TB_PROFESSOR_REG;
CREATE TABLE TB_PROFESSOR_REG(
  PROFESSOR_REG_CODE varchar(20),     -- 교수담당과목 정보코드
  COURSE_CODE varchar(20),       -- 과목코드
  USER_CODE varchar(20),          -- 유저코드

  CONSTRAINT TB_PROFESSOR_REG_PK PRIMARY KEY(PROFESSOR_REG_CODE)
);


DROP TABLE TB_POST;
CREATE TABLE TB_POST(
ZIPCODE varchar(10)
,SIDO varchar(50)
,GUGUN varchar(100)
,DONG varchar(100)
,BUNJI varchar(50)
,SEQ int(11) PRIMARY KEY
);

commit;